runtime: python39 # Use the latest runtime
entrypoint: gunicorn -b :$PORT app:app # Adjust based on your Flask app structure

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
